export const FETCH_ALL_VIDEOS_SUCCESS = 'FETCH_ALL_VIDEOS_SUCCESS'
export const FETCH_ALL_VIDEOS_FAILURE = 'FETCH_ALL_VIDEOS_FAILURE'
export const FETCH_ALL_VIDEOS_SET_LOADING_TRUE = 'FETCH_ALL_VIDEOS_SET_LOADING_TRUE'
export const FETCH_ALL_VIDEOS_SET_LOADING_FALSE = 'FETCH_ALL_VIDEOS_SET_LOADING_FALSE'

export const CREATE_VIDEO = 'CREATE_VIDEO'
export const CREATE_VIDEO_SET_LOADING_TRUE = 'CREATE_VIDEO_SET_LOADING_TRUE'
export const CREATE_VIDEO_SET_LOADING_FALSE = 'CREATE_VIDEO_SET_LOADING_FALSE'
