export const FETCH_ALL_PATIENTS_SUCCESS = 'FETCH_ALL_PATIENTS_SUCCESS';
export const FETCH_ALL_PATIENTS_FAILURE = 'FETCH_ALL_PATIENTS_FAILURE';
export const FETCH_ALL_PATIENTS_SET_LOADING_TRUE = 'FETCH_ALL_PATIENTS_SET_LOADING_TRUE';
export const FETCH_ALL_PATIENTS_SET_LOADING_FALSE = 'FETCH_ALL_PATIENTS_SET_LOADING_FALSE'