export const FETCH_ALL_PATIENTS_SUCCESS = 'FETCH_ALL_PATIENTS_SUCCESS'
export const FETCH_ALL_PATIENTS_FAILURE = 'FETCH_ALL_PATIENTS_FAILURE'
export const FETCH_ALL_PATIENTS_SET_LOADING_TRUE = 'FETCH_ALL_PATIENTS_SET_LOADING_TRUE'
export const FETCH_ALL_PATIENTS_SET_LOADING_FALSE = 'FETCH_ALL_PATIENTS_SET_LOADING_FALSE'

export const CREATE_PATIENT_SUCCESS = 'CREATE_PATIENT_SUCCESS'
export const CREATE_PATIENT_FALSE = 'CREATE_PATIENT_FALSE'
export const CREATE_PATIENT_SET_LOADING_TRUE = 'CREATE_PATIENT_SET_LOADING_TRUE'
export const CREATE_PATIENT_SET_LOADING_FALSE = 'CREATE_PATIENT_SET_LOADING_FALSE'
