export const CHANGE_LOGGED_IN = 'CHANGE_LOGGED_IN';
export const USER_STATUS_IS_AUTH = 'USER_STATUS_IS_AUTH'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SET_LOADING_TO_TRUE = 'SET_LOADING_TO_TRUE'
export const SET_LOADING_TO_FALSE = 'SET_LOADING_TO_FALSE'