export const CHECK_USER_AUTH_STATUS_ON_APP_LOAD = 'CHECK_USER_AUTH_STATUS_ON_APP_LOAD'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const SET_LOADING_TO_TRUE = 'SET_LOADING_TO_TRUE'
export const SET_LOADING_TO_FALSE = 'SET_LOADING_TO_FALSE'