export const FETCH_ALL_KITS_SUCCESS = 'FETCH_ALL_KITS_SUCCESS';
export const FETCH_ALL_KITS_FAILURE = 'FETCH_ALL_KITS_FAILURE';
export const FETCH_ALL_KITS_SET_LOADING_TRUE = 'FETCH_ALL_KITS_SET_LOADING_TRUE';
export const FETCH_ALL_KITS_SET_LOADING_FALSE = 'FETCH_ALL_KITS_SET_LOADING_FALSE'