export const FETCH_ALL_TESTS_SUCCESS = 'FETCH_ALL_TESTS_SUCCESS';
export const FETCH_All_TESTS_SET_LOADING_TRUE = 'FETCH_All_TESTS_SET_LOADING_TRUE';
export const FETCH_All_TESTS_SET_LOADING_FALSE = 'FETCH_All_TESTS_SET_LOADING_FALSE';

export const FETCH_TESTS_BY_ID_SUCCESS = 'FETCH_TESTS_BY_ID_SUCCESS';
export const CLEAN_TESTS_BY_ID = 'CLEAN_TESTS_BY_ID';
export const FETCH_TESTS_BY_ID_SET_LOADING_TRUE = 'FETCH_TESTS_BY_ID_SET_LOADING_TRUE';
export const FETCH_TESTS_BY_ID_SET_LOADING_FALSE = 'FETCH_TESTS_BY_ID_SET_LOADING_FALSE';
