export const FETCH_PLAN_BY_ID_SUCCESS = 'FETCH_PLAN_BY_ID'
export const FETCH_PLAN_BY_ID_SET_LOADING_TRUE = 'FETCH_PLAN_BY_ID_SET_LOADING_TRUE'
export const FETCH_PLAN_BY_ID_SET_LOADING_FALSE = 'FETCH_PLAN_BY_ID_SET_LOADING_FALSE'

export const CREATE_PLAN_SUCCESS = 'CREATE_PLAN_SUCCESS'


export const EDIT_PLAN_BY_ID_SUCCESS = 'EDIT_PLAN_BY_ID_SUCCESS'
export const EDIT_PLAN_BY_ID_SET_LOADING_TRUE = 'EDIT_PLAN_BY_ID_SET_LOADING_TRUE'
export const EDIT_PLAN_BY_ID_SET_LOADING_FALSE = 'EDIT_PLAN_BY_ID_SET_LOADING_FALSE'
