export const FETCH_ALL_PLANS_SUCCESS = 'FETCH_ALL_PLANS_SUCCESS';
export const FETCH_ALL_PLANS_FAILURE = 'FETCH_ALL_PLANS_FAILURE';
export const FETCH_ALL_PLANS_SET_LOADING_TRUE = 'FETCH_ALL_PLANS_SET_LOADING_TRUE';
export const FETCH_ALL_PLANS_SET_LOADING_FALSE = 'FETCH_ALL_PLANS_SET_LOADING_FALSE';
export const CLEAN_PLANS_BY_ID = 'CLEAN_PLANS_BY_ID';
